############################################
# version : cnlubo/centos-mysql5.7:v1
# desc : 扩展版本安装 msyql5.7
############################################
FROM cnlubo/mycentos:v1
LABEL maintainer="bolu20080314@gmail.com" \
    provider="cnak47"



COPY build /build
RUN chmod +x /build/*.sh && \
    /build/prepare.sh && \
    /build/install.sh && \
	/build/cleanup.sh



# Define default command
#CMD ["/usr/local/bin/zsh"]
