apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openelb-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openelb-manager-role
subjects:
- kind: ServiceAccount
  name: openelb-admission
  namespace: openelb-system

