apiVersion: batch/v1
kind: Job
metadata:
  name: openelb-admission-create
  namespace: openelb-system
spec:
  template:
    metadata:
      name: openelb-admission-create
    spec:
      containers:
      - args:
        - create
        - --host=openelb-admission,openelb-admission.$(POD_NAMESPACE).svc
        - --namespace=$(POD_NAMESPACE)
        - --secret-name=openelb-admission
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # If you cannot access "k8s.gcr.io/ingress-nginx/kube-webhook-certgen", you can replace it with "kubespheredev/kube-webhook-certgen"
        image: k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1
        imagePullPolicy: IfNotPresent
        name: create
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
      serviceAccountName: openelb-admission

