apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openelb-admission
  namespace: openelb-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openelb-admission
subjects:
- kind: ServiceAccount
  name: openelb-admission
  namespace: openelb-system

