---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: traefik-ingress-configmap
#   namespace: traefik
# data:
#   traefik.toml: |
#     defaultEntryPoints = ["https","http"]
#     [entryPoints]
#       [entryPoints.http]
#       address = ":80"
#       [entryPoints.https]
#       address = ":443"
#         [entryPoints.https.tls]
#           [[entryPoints.https.tls.certificates]]
#           CertFile = "/ssl/tls.crt"
#           KeyFile = "/ssl/tls.key"
#       [entryPoints.traefik]
#         address = ":8080"
#         [entryPoints.traefik.auth.basic]
#         users = ["admin:$apr1$tUQT3hya$55t73RGXDWrzSwsClWTr3."]
#     [kubernetes]
#       [kubernetes.ingressEndpoint]
#         publishedService = "traefik/traefik-ingress-controller-http-service"
#     [ping]
#     entryPoint = "http"
#     [api]
#     entryPoint = "traefik"
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik
data:
  traefik-config.yaml: |-
    serversTransport:
      insecureSkipVerify: true  ## 忽略验证代理服务的 TLS 证书
    api:
      insecure: true            ## 允许 HTTP 方式访问 API
      dashboard: false          ## 不启用 Dashboard UI
      debug: true               ## 启用 Debug 模式
    providers:
      kubernetescrd:            ## 启用 Kubernetes CRD 方式来配置路由规则
        ingressclass: traefik-v2.5
      kubernetesingress:        ## 启动 Kubernetes Ingress 方式来配置路由规则
        ingressclass: traefik-v2.5
    log:
      filePath: "/etc/traefik/logs/traefik.log"              ## 设置调试日志文件存储路径，如果为空则输出到控制台
      level: error                ## 设置调试日志级别
      format: json                ## 设置调试日志格式
    accessLog:
      filePath: "/etc/traefik/logs/access.log"              ## 设置访问日志文件存储路径，如果为空则输出到控制台
      format: json              
      bufferingSize: 0         
      filters:
        retryAttempts: true     ## 设置代理访问重试失败时，保留访问日志
        minDuration: 10         ## 设置保留请求时间超过指定持续时间的访问日志
      fields:                   ## 设置访问日志中的字段是否保留（keep 保留、drop 不保留）
        defaultMode: keep       ## 设置默认保留访问日志字段
        names:                  ## 针对访问日志特别字段特别配置保留模式
          ClientUsername: drop
        headers:                ## 设置 Header 中字段是否保留
          defaultMode: keep     ## 设置默认保留 Header 中字段
          names:                ## 针对 Header 中特别字段特别配置保留模式
            User-Agent: redact
            Authorization: drop
            Content-Type: keep
