---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-certs-pvc
  namespace: traefik
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Mi
