version: "2"

services:
  postgresql:
    image: cnlubo/postgresql:14
    environment:
      PG_PASSWORD: 12345678
      DB_EXTENSION: unaccent,pg_trgm
      DB_USER: redmine
      DB_PASS: admin12345678
    volumes:
      - /opt/redmine/postgresql:/var/lib/postgresql

  redmine:
    build: ./
    image: sameersbn/redmine:5.0.3-1
    depends_on:
      - postgresql
    environment:
      - TZ=Asia/Shanghai
      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=redmine
      - DB_PASS=admin12345678
      - DB_NAME=redmine_production

      - REDMINE_PORT=10083
      - REDMINE_HTTPS=false
      - REDMINE_RELATIVE_URL_ROOT=/redmine
      - REDMINE_SECRET_TOKEN=

      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15

      - REDMINE_CONCURRENT_UPLOADS=2

      - REDMINE_BACKUP_SCHEDULE=
      - REDMINE_BACKUP_EXPIRY=
      - REDMINE_BACKUP_TIME=

      - SMTP_ENABLED=false
      - SMTP_METHOD=smtp
      - SMTP_DOMAIN=www.example.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=mailer@example.com
      - SMTP_PASS=password
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=:login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_INTERVAL=30

    ports:
      - "10083:80"
    volumes:
      - /opt/redmine/redmine:/home/redmine/data
      - /opt/redmine/redmine/redmine-logs:/var/log/redmine
