version: "3.2"
services:
  ch-server-11:
    container_name: ch-server-11
    hostname: ch-server-11
    image: yandex/clickhouse-server:20.6.4.44
    volumes:
      - /Users/ak47/Documents/docker/ch-server/ch1/conf/config.d/macros.xml:/etc/clickhouse-server/config.d/macros.xml
      - /Users/ak47/Documents/docker/ch-server/ch1/conf/config.xml:/etc/clickhouse-server/config.xml
      - /Users/ak47/Documents/docker/ch-server/ch1/conf/config.d/docker_related_config.xml:/etc/clickhouse-server/config.d/docker_related_config.xml
      - /Users/ak47/Documents/docker/ch-server/ch1/conf/users.xml:/etc/clickhouse-server/users.xml
      - /Users/ak47/Documents/docker/ch-server/ch1/conf/metrika.xml:/etc/clickhouse-server/metrika.xml
      - /Users/ak47/Documents/docker/ch-server/ch1/data:/var/lib/clickhouse
      - /Users/ak47/Documents/docker/ch-server/ch1/log/clickhouse-server.log:/var/log/clickhouse-server/clickhouse-server.log
      - /Users/ak47/Documents/docker/ch-server/ch1/log/clickhouse-server.err.log:/var/log/clickhouse-server/clickhouse-server.err.log
    ports:
      - 18123:8123
      - 9011:9000
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  ch-server-12:
    container_name: ch-server-12
    hostname: ch-server-12
    image: yandex/clickhouse-server:20.6.4.44
    volumes:
      - /Users/ak47/Documents/docker/ch-server/ch2/conf/config.d/macros.xml:/etc/clickhouse-server/config.d/macros.xml
      - /Users/ak47/Documents/docker/ch-server/ch2/conf/config.xml:/etc/clickhouse-server/config.xml
      - /Users/ak47/Documents/docker/ch-server/ch2/conf/config.d/docker_related_config.xml:/etc/clickhouse-server/config.d/docker_related_config.xml
      - /Users/ak47/Documents/docker/ch-server/ch2/conf/users.xml:/etc/clickhouse-server/users.xml
      - /Users/ak47/Documents/docker/ch-server/ch2/conf/metrika.xml:/etc/clickhouse-server/metrika.xml
      - /Users/ak47/Documents/docker/ch-server/ch2/data:/var/lib/clickhouse
      - /Users/ak47/Documents/docker/ch-server/ch2/log/clickhouse-server.log:/var/log/clickhouse-server/clickhouse-server.log
      - /Users/ak47/Documents/docker/ch-server/ch2/log/clickhouse-server.err.log:/var/log/clickhouse-server/clickhouse-server.err.log

    ports:
      - 28123:8123
      - 9012:9000
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  # ch-server-21:
  #   container_name: ch-server-21
  #   hostname: ch-server-21
  #   image: yandex/clickhouse-server
  #   volumes:
  #     - ./config.xml:/etc/clickhouse-server/config.d/local.xml
  #     - ./macros21.xml:/etc/clickhouse-server/config.d/macros.xml
  #   ports:
  #     - 9021:9000
  # ch-server-22:
  #   container_name: ch-server-22
  #   hostname: ch-server-22
  #   image: yandex/clickhouse-server
  #   volumes:
  #     - ./config.xml:/etc/clickhouse-server/config.d/local.xml
  #     - ./macros22.xml:/etc/clickhouse-server/config.d/macros.xml
  #   ports:
  #     - 9022:9000
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: zookeeper:3.6.1
