---
apiVersion: v1
kind: Service
metadata:
  name: nginx-node-port
  namespace: default
spec:
  type: NodePort
  selector:
    app: nginx-node-port
  ports:
    - protocol: TCP
      nodePort: 30123
      port: 8080
      name: http
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-node-port
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-node-port
  template:
    metadata:
      labels:
        app: nginx-node-port
    spec:
      containers:
        - image: nginxinc/nginx-unprivileged
          name: nginx-node-port
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
             memory: "1Gi"
             cpu: "80m"
            limits: 
             memory: "1Gi" 
             cpu: "80m"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 3
