---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  # - port: 443
  #   name: https
  #   protocol: TCP
  #   targetPort: 443
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    # kubernetes.io/ingress.class: traefik
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "true"
    # traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    # traefik.ingress.kubernetes.io/redirect-entry-point: https
    # traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  tls:
  - hosts:
    - my.nginx.svc
    secretName: nginx-secret
  rules:
  - host: my.nginx.svc
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
