#cloud-config
#
# This is an example file to automatically configure resolv.conf when the
# instance boots for the first time.
#
# Ensure that your yaml is valid and pass this as user-data when starting
# the instance. Also be sure that your cloud.cfg file includes this
# configuration module in the appropriate section.

---
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
package_update: true
packages:
  - docker
  - avahi-daemon
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
runcmd:
  - sudo curl -fsSL https://get.docker.com | sudo bash
  - sudo systemctl enable docker
  - sudo sed -i "s@^ExecStart.*@#&@" /lib/systemd/system/docker.service
  - sudo sed -i "s@^#ExecStart.*@&\nExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2375 --containerd=/run/containerd/containerd.sock@" /lib/systemd/system/docker.service
  - sudo systemctl daemon-reload
  - sudo systemctl restart docker.service
  - sudo groupadd docker
  - sudo usermod -aG docker ubuntu

bootcmd:
  - printf "[Resolve]\nDNS=8.8.8.8" > /etc/systemd/resolved.conf
  - [systemctl, restart, systemd-resolved]
