apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-rancher-ingress
  # 需要使用证书的应用所在的命名空间
  namespace: cattle-system
spec:
  secretName: tls-rancher-ingress
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - soft Inc.
  commonName: rancher.test321.com
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - rancher.test321.com
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
